SciML/NeuralPDE.jl

test/NNPDEHan_tests.jl, test/NNPDENS_tests.jl
-added test for Nonlinear Black-Scholes Equation with Default Risk
-fixed test for Hamilton Jacobi Bellman Equation
=> added test for Nonlinear Black-Scholes Equation with Default Risk

README.md, src/pde_solve_ns.jl, test/NNPDENS_tests.jl
I noticed that a lot of the options violated the DifferentialEquations.jl style, so this update makes them more in line with what users would expect.
=> fix options to diffeq style

src/pde_solve_ns.jl, test/NNPDEHan_tests.jl, test/NNPDENS_tests.jl
issue https://github.com/JuliaDiffEq/NeuralNetDiffEq.jl/issues/29
=> move the call of X.data inside the method

src/ode_solve.jl, test/NNPDEHan_tests.jl, test/NNPDENS_tests.jl
Fix some issues in ode_solver.  
The method didn't work with some type of equations(examples:f = (u,p,t) -> 1.01*u and fitzhugh nagumo model)
=> fix ode_solver

Project.toml, src/NeuralNetDiffEq.jl, src/ode_solve.jl
```julia
using OrdinaryDiffEq, DiffEqFlux, NeuralNetDiffEq, Plots, Optim, Flux
function f(du,u,p,t)
du[1] = p[1]*u[1] - p[2]*u[1]*u[2]
du[2] = -p[3]*u[2] + p[4]*u[1]*u[2]
end
function f(u,p,t)
[p[1]*u[1] - p[2]*u[1]*u[2],-p[3]*u[2] + p[4]*u[1]*u[2]]
end
p = Float32[1.5,1.0,3.0,1.0]
u0 = Float32[1.0,1.0]
prob = ODEProblem(f,u0,(0f0,3f0),p)
prob_oop = ODEProblem{false}(f,u0,(0f0,3f0),p)
true_sol = solve(prob,Tsit5())
N = 128
chain = FastChain(FastDense(1,N,tanh), FastDense(N,N,tanh), FastDense(N,N,tanh), FastDense(N,length(u0)))
opt = ADAM(0.000001)
θ = DiffEqFlux.initial_params(chain)
sol  = solve(prob_oop,NeuralNetDiffEq.NNODE(chain,opt,θ,autodiff=true),maxiters = 10000, verbose = true, dt=1/5f0)
plot(true_sol)
plot!(sol)
using CuArrays
function f(u,p,t)
cu([p[1]*u[1] - …
```
=> initial parameter choices and GPU compatibility

src/ode_solve.jl
The dimension mismatch error is made more explanatory. #80
=> Improving the error message for DimensionMismatch

src/NeuralNetDiffEq.jl, src/kolmogorov_solve.jl, test/NNKolmogorov_tests.jl, test/NNODE_tests.jl, test/NNPDEHan_tests.jl, test/NNPDENS_tests.jl
Added noise_rate_prototype as a field for non Diagonal Noise in both SDE and KolmogorovPDE Problems.
=> Added noise_rate_prototype for Non Diagonal Noise.

.travis.yml, Project.toml, src/NeuralNetDiffEq.jl, src/ode_solve.jl, src/pinns_pde_solve.jl, test/NNODE_tests.jl, test/NNPDE_tests.jl, test/runtests.jl
=> General PDE solving with NNs fix revert

docs/make.jl, docs/src/examples/optimal_stopping.md, docs/src/kolmogorov_on_gpu.md
=> Documentation for Optimal Stopping Time

src/NeuralPDE.jl, src/pinns_pde_solve.jl, test/NNPDE_tests.jl
in addition to the Dirichlet condition, we can now use any condition in any form.
=> improve boundary condition

Project.toml, src/NeuralPDE.jl, src/pinns_pde_solve.jl, test/NNPDE_tests.jl
NNPDEProblem -> OptimizationProblem
=> Slight refactoring of PINNs

src/NeuralPDE.jl, src/pinns_pde_solve.jl, test/NNPDE_tests.jl
-added Stochastic Loss Function
-removed `NNODE`  and `solver` overload
-refactoring`discretize` and `PhysicsInformedNN`
-use  GalacticOptim solver
=> Stochastic Loss Function PINNS

docs/src/examples/pinns_example.md, src/NeuralPDE.jl, src/pinns_pde_solve.jl, test/NNPDE_tests.jl
=> Mixed derivatives

src/NeuralPDE.jl, src/ode_solve.jl, test/NNODE_tests.jl
This algorithm seems to not be matching the docs, just in name. Seems like a mistake.
=> Fix NNDE to NNODE

src/pinns_pde_solve.jl, test/NNPDEHan_tests.jl, test/NNPDE_tests.jl, test/NNPDE_tests_gpu.jl
improve performance of derivative
=> Improve performance of derivative

README.md, docs/src/examples/100_HJB.md, docs/src/examples/blackscholes.md, docs/src/examples/kolmogorovbackwards.md, docs/src/examples/nnrode_example.md, docs/src/examples/optimal_stopping_american.md, docs/src/examples/pinns_example.md, docs/src/index.md, docs/src/solvers/deep_fbsde.md, docs/src/solvers/kolmogorovbackwards_solver.md, docs/src/solvers/ode.md, docs/src/solvers/pinn.md, src/NeuralPDE.jl, src/kolmogorov_solve.jl, src/pde_solve.jl, src/pde_solve_ns.jl, src/pinns_pde_solve.jl, src/stopping_solve.jl
Stylistic revision, typos, punctuation, references, etc.
=> Documentation changes

README.md
fixed the error with `discretization` in 2D Poisson equation example
=> Fix Poisson example in README

docs/src/examples/pinns_example.md
The previous code was causing problems when i was recompiling it in my system. So I am making some changes in the docs and I will complete all the changes by tomorrow evening
=> fixed some problems in 2D poisson equation

docs/make.jl, docs/src/pinn/2D.md, docs/src/pinn/low_level.md, docs/src/pinn/poisson.md, docs/src/pinn/wave.md
=> Docs: Tutorial misleading naming

docs/src/pinn/parm_estim.md
=> Docs estim params

docs/src/pinn/debugging.md, docs/src/pinn/low_level.md, src/pinns_pde_solve.jl, test/NNPDE_tests.jl
https://github.com/SciML/NeuralPDE.jl/issues/294
=> Systems of one equation

README.md, src/NeuralPDE.jl
https://github.com/SciML/NeuralPDE.jl/issues/305
=> Demo failure

docs/src/solvers/pinns.md, src/NeuralPDE.jl, src/pinns_pde_solve.jl, test/NNPDE_tests.jl, test/NNPDE_tests_gpu.jl
https://github.com/SciML/NeuralPDE.jl/issues/288
=> QuasiRandomTraining, on every training iteration, it is generated a new quasirandom sample

docs/src/solvers/pinns.md, src/pinns_pde_solve.jl, test/NNPDE_tests.jl
https://github.com/SciML/NeuralPDE.jl/issues/296
=> Allow number of boundary points

docs/src/pinn/debugging.md, docs/src/pinn/low_level.md, src/pinns_pde_solve.jl, test/NNPDE_tests.jl, test/NNPDE_tests_gpu.jl
https://github.com/SciML/NeuralPDE.jl/issues/320
=> The loss function for each equation

docs/src/pinn/debugging.md, src/NeuralPDE.jl, src/pinns_pde_solve.jl, test/NNPDE_tests.jl, test/NNPDE_tests_gpu.jl
https://github.com/SciML/NeuralPDE.jl/issues/322
=> Extract num of points for quadrature.jl methods

docs/src/pinn/system.md
https://github.com/SciML/NeuralPDE.jl/issues/302
=> Fix PDAE system example and derivative neural network approximation

src/pinns_pde_solve.jl
https://github.com/SciML/NeuralPDE.jl/issues/337
=> fix broadcast piracy

docs/src/pinn/system.md
#332 Added two concrete examples of systems of PDEs – one linear parabolic and one nonlinear elliptic. Still want to add a nonlinear hyperbolic system, but wanted to open the PR
=> More examples of systems of PDEs #332

docs/src/pinn/wave.md
=> Added damped wave example #327

docs/src/pinn/wave.md
Sorry, I had a typo in the codeblock so it rendered it as regular text
=> Fixed 1D damped wave example

docs/src/pinn/2D.md, docs/src/pinn/3rd.md, docs/src/pinn/fp.md, docs/src/pinn/ks.md, docs/src/pinn/low_level.md, docs/src/pinn/parm_estim.md, docs/src/pinn/poisson.md, docs/src/pinn/system.md, docs/src/pinn/wave.md
This PR latexifies the equations in the PINN Tutorials section of the docs.
=> LaTeXify equations in Docs/PINN Tutorials

docs/src/examples/optimal_stopping_american.md
For some reason the modified black Scholes equation also doesn't seem to be rendering correctly
=> Update optimal_stopping_american.md images and equations

docs/src/pinn/wave.md
I improved the previous damped wave results in the docs with adaptive derivative (also fixed some typos in the equation)
=> Improve damped wave results in docs

docs/src/pinn/fp.md, test/NNPDE_tests.jl
-update Fokker-Planck https://github.com/SciML/NeuralPDE.jl/issues/279
-add Approximation of function tests
=> Approximation function tests and update Fokker-Planck 

docs/src/pinn/integro_diff.md
It should say `@named pde_system...` in the IDE doc.
=> fix IDE doc

.github/workflows/CI.yml, test/forward_tests.jl, test/runtests.jl
https://github.com/SciML/NeuralPDE.jl/issues/369
=> Forward tests

src/pinns_pde_solve.jl
https://github.com/SciML/NeuralPDE.jl/issues/418
=> Fix first IDE test

docs/src/solvers/pinns.md
minor doc change based on https://github.com/SciML/NeuralPDE.jl/issues/437
=> add parameterless_type_θ to get_phi doc

src/NeuralPDE.jl
https://github.com/SciML/NeuralPDE.jl/issues/474
=> TerminalPDEProblem REPL error

docs/src/pinn/wave.md
I added a missing definition of `Dx`
=> fix wave eq. example

docs/src/pinn/wave.md
I updated the script now the prediction result matches the script
https://github.com/SciML/NeuralPDE.jl/issues/478
=> Update damped wave docs

docs/src/solvers/pinns.md
=> Minor typos in API Documentation

docs/src/pinn/integro_diff.md
In this PR:
- Integral variables have been swapped.
- Render "for" as plain text.
$$
... \int_{0}^{x}u(t)dt = 1 for t \geq 0 
$$
$$
... \int_{0}^{t}u(x)dx = 1 \ \text{for} \ t \geq 0
$$
Closes #517
=> Fix variables in 1-dimensional IDE example

src/ode_solve.jl, src/training_strategies.jl, test/NNODE_tests.jl
This puts it more in line with the modernized PDE training setups and serves as a much better example for proper coding style
=> Overhaul NNODE

src/pinns_pde_solve.jl, test/NNPDE_tests.jl, test/additional_loss_tests.jl, test/direct_function_tests.jl, test/forward_tests.jl
Removed the extra non-interface function
=> Simplify all of symbolic discretize into just symbolic discretize

src/adaptive_losses.jl, src/discretize.jl, src/pinn_types.jl
Fixes https://github.com/SciML/NeuralPDE.jl/issues/489
=> Generalize the adaptive loss interface

src/discretize.jl
https://github.com/SciML/NeuralPDE.jl/issues/577
=> fix grid strategy with PDE systems 

src/pinn_types.jl, src/symbolic_utilities.jl, test/forward_tests.jl
=> Use different step sizes for different orders of derivatives

src/discretize.jl, src/training_strategies.jl
=> Correct sampling

.buildkite/pipeline.yml, src/training_strategies.jl
This should handle the regression in the adapting that occurs from the update of CUDA.jl https://buildkite.com/julialang/neuralpde-dot-jl/builds/1433#0185ddd7-0cb9-49f4-97df-8147ca22efbc
=> Use the parameterless type for doing adapting

docs/src/tutorials/gpu.md, test/NNPDE_tests_gpu_Lux.jl
This is the continuation of #646 for a few more spots in the code, notably in a test that provokes an error in CI.
=>  ComponentArray ERROR in Lux (2)

src/discretize.jl
=> Log additional loss

README.md
NeuralAdaptor should be fixed.
=> Test new DiffEqBase

.gitignore, Project.toml, src/BPINN_ode.jl, src/advancedHMC_MCMC.jl
=> BNNODE bug fix, faster MvNormal pdf definition

src/dgm.jl, test/dgm_test.jl
Small cleanup PR after #802 
Also, removing deprecated things in DGM tests (https://github.com/SciML/NeuralPDE.jl/actions/runs/8143243633/job/22254650391#step:6:862). Hopefully it should make tests faster.
=> chore: format docstrings of DGM to make it consistent with others

docs/make.jl, docs/src/tutorials/dgm.md, src/BPINN_ode.jl, src/advancedHMC_MCMC.jl
=> docs: fix rendering

docs/src/examples/complex.md, docs/src/tutorials/Lotka_Volterra_BPINNs.md, docs/src/tutorials/dae.md, docs/src/tutorials/ode.md, docs/src/tutorials/ode_parameter_estimation.md, src/training_strategies.jl
=> Docstring typo fixes

.github/dependabot.yml
Ref: https://github.com/SciML/NeuralPDE.jl/pull/868#issuecomment-2186826750
=> build: ignore patch versions of typos gha in dependabot

src/eltype_matching.jl, test/NNPDE_tests.jl
Fixes https://github.com/SciML/NeuralPDE.jl/issues/906
=> Real valued datagen from GridTraining when boundary points are trivial

test/direct_function_tests.jl
This PR adds two regression test cases to `direct_function_tests.jl` to document and safeguard against known failures in NeuralPDE.jl when handling edge-case boundary conditions.
Details:
- `@testitem "Trivial BC [0 ~ 0] fails for some training strategies"`:
Confirms that the boundary condition `[0 ~ 0]` causes `discretize()` to throw an `ArgumentError` when used with `StochasticTraining` and `QuasiRandomTraining`. This behavior is consistent with what was originally reported in issue #911  
- `@testitem "Empty boundary condition [] fails in solve phase"`:
Confirms that providing no boundary conditions at all (`[]`) results in a `MethodError` during the call to `solve(...)` across all training strategies.
These test items codify the current behavior for CI purposes. If these issues are …
=> Add regression tests for [0 ~ 0] and empty boundary conditions

docs/src/manual/pinns.md
=> Use more reproducible tex rather than rendered formula image in pinns.md
