src/NeuralNetDiffEq.jl, src/kolmogorov_solve.jl, src/stopping_solve.jl, test/NNKolmogorov_tests.jl
1. Add trajectories to the solver directly
2. Specify algorithm to stopping_solve.jl and kolmogorov_solve.jl to avoid wrong solver calls for SDEProblem
=> Add trajectories to Kolmogorov Solver and fix bugs.

README.md
Awesome package, thank you! Just noticed there's a missing `using DiffEqFlux` when directly running the first example in the README.md
=> Adds missing DiffEqFlux import in first example

src/NeuralPDE.jl, src/pinns_pde_solve.jl
```julia
@parameters x
@variables u(..)
@derivatives Dxxx'''~x
@derivatives Dx'~x
eq = Dxxx(u(x)) ~ cos(pi*x)
bcs = [u(0.) ~ 0.0,
u(1.) ~ cos(pi),
Dx(u(1.)) ~ 1.0]
domains = [x ∈ IntervalDomain(0.0,1.0)]
dx = 0.05
chain = FastChain(FastDense(1,8,Flux.σ),FastDense(8,1))
discretization = NeuralPDE.PhysicsInformedNN(chain)
pde_system = PDESystem(eq,bcs,domains,[x],[u])
prob = NeuralPDE.symbolic_discretize(pde_system,discretization)
pde_loss, bcs_loss = prob
```
```julia
julia> pde_loss
:((cord, var"##θ#429", phi, derivative, u_arr, u_d_arr)->begin
#=  =#
#=  =#
begin
(u,) = (u_arr[1],)
(u_d,) = (u_d_arr[1],)
let (x,) = (cord[1],)
[derivative(phi, u_d, [x], Array{Float32,1}[[0.0049215667], [0.0049215667], [0.0049215667]], 3, var"##θ#429") - (cos)((*)(π, x))]
end
end
end)
```
```julia
julia> …
```
=> Symbolic Discretization Version

src/pinns_pde_solve.jl
The previous choice wasn't even quasi-random.
=> Default quasi-random to Latin Hypercubes

src/NeuralPDE.jl, src/pinns_pde_solve.jl, test/NNPDE_tests.jl
`additional_loss` didn't work with `param_estim=false` because theta is truncated and this is only needed when `param_estim=true`
https://github.com/SciML/NeuralPDE.jl/blob/d42dbd54072567096407e990c8685a63ea7d1b13/src/pinns_pde_solve.jl#L938-L941
=> fix additional_loss

src/pinns_pde_solve.jl
https://github.com/SciML/NeuralPDE.jl/issues/390 I changed the loop into a map to improve integral performance. Nothing else is different since the map gives the same inputs to `integration_` (but hopefully it does so a bit more efficiently). If you think there are other quick wins here, let me know. Happy to help.
I will debug this a bit but wanted to open the PR now.
=> Increase integral performance with map

src/NeuralPDE.jl, src/pinns_pde_solve.jl, test/IDE_tests.jl
Some compound integrals are working. Others show different errors ranging from problems with the inner representation to ChainRulesCore errors. Will investigate and try to fix it.
=> Support for compound integrals

src/pinns_pde_solve.jl
The previous way to get `integrating_depvars` was not working for all cases. This is an attempt to improve it.
this for example wouldn’t work in master but works here
```
@parameters x
@variables u(..) w(..)
Dx = Differential(x)
Ix = Integral(x in DomainSets.ClosedInterval(1, x))
Ii = Integral(x in DomainSets.ClosedInterval(0, 1))
eqs =  [Ix(u(x)*w(x)) ~ log(abs(x)),
Dx(w(x)) ~ -2/(x^3),
u(x) ~ x + Ix(u(x)/x)]
bcs = [u(1.) ~ 1.0, w(1.) ~ 1.0]
domains = [x ∈ Interval(1.0,2.0)]
chains = [FastChain(FastDense(1,15,Flux.σ),FastDense(15,1)) for _ in 1:2]
initθ = map(chain -> Float64.(DiffEqFlux.initial_params(chain)),chains)
strategy_ = NeuralPDE.GridTraining(0.1)
discretization = NeuralPDE.PhysicsInformedNN(chains,
strategy_;
init_params = initθ
)
@named pde_system = …
```
=> Improve integrating_depvars so it works more generally

docs/src/pinn/debugging.md
Hi, the example in the debugging documentation does not run with the current version of NeuralPDE (v4.4.0). This was fixed by adding `dict_depvar_input` and `integral`, which are new arguments for some methods of the low-level API.
=> Fix debugging docs

test/direct_function_tests.jl
Can make it more robust later, but it's clearly just an RNG network thing in one test on v1.6 (and only v1.6 because the RNG change in v1.7)
=> Better RNG seed?

src/pinn_types.jl
This will help with both stability and performance. Also it makes the linear scaling of the derivative with numerical differentiation explicit, as opposed to the polynomial scaling of AD, so this should be the fast mode. This also then shows how to specialize for Diffractor in the near future.
Examples of improved stability:
```julia
using NeuralPDE, Flux, Optimization, OptimizationOptimJL, DiffEqFlux
import ModelingToolkit: Interval
@parameters x y
@variables u(..)
Dxx = Differential(x)^2
Dyy = Differential(y)^2
eq  = Dxx(u(x,y)) + Dyy(u(x,y)) ~ -sin(pi*x)*sin(pi*y)
bcs = [u(0,y) ~ 0.0, u(1,y) ~ 0.0,
u(x,0) ~ 0.0, u(x,1) ~ 0.0]
domains = [x ∈ Interval(0.0,1.0),
y ∈ Interval(0.0,1.0)]
dim = 2 # number of dimensions
chain = FastChain(FastDense(dim,16,Flux.σ),FastDense(16,16,Flux.σ),FastDens …
```
=> Specialize higher order derivatives 

docs/src/examples/linear_parabolic.md, docs/src/examples/nonlinear_elliptic.md, docs/src/examples/nonlinear_hyperbolic.md, docs/src/examples/wave.md, docs/src/tutorials/derivative_neural_network.md, docs/src/tutorials/low_level.md, docs/src/tutorials/param_estim.md, docs/src/tutorials/systems.md, src/discretize.jl, src/pinn_types.jl, test/IDE_tests.jl, test/NNPDE_tests.jl, test/additional_loss_tests.jl
Changes from `depvar_1` for the ith neural network to `x` if it's `[x(t),y(t),z(t)]`. This should make it a lot easier to understand the indexing structure: `res.u.depvar.y` etc. 
This builds on https://github.com/SciML/NeuralPDE.jl/pull/565 and should be the last change for the v5 release.
=> Use dependent variable naming in the indexing 

docs/src/tutorials/gpu.md
ComponentArray in Lux has been removed, so I used ComponentArrays.jl to connect gpu. "ps = ps |> Lux.ComponentArray |> gpu .|> Float64" has been rewriten as "ps = ps |> ComponentArray |> gpu .|> Float64" It can work on my PC
=> ComponentArray ERROR in Lux

src/ode_solve.jl, test/NNODE_tests.jl
ODE worked only with a vector with one element. Fixed and added the test for the ODE system
=> Fix ODEs system and add test

src/ode_solve.jl, src/training_strategies.jl, test/NNODE_tests.jl, test/NNODE_tstops_test.jl
Renaming would be consistent with other strategies `StochasticTraining`, `QuasiRandomTraining` etc. as it contains the number of points.
Cleaning up `tstops_loss` to avoid redundant function evaluation.
=> Rename `samples` field of `WeightedIntervalTraining` to `points` and clean `tstops_loss` logic

docs/pages.jl, docs/src/examples/Lotka_Volterra_BPINNs.md, docs/src/examples/ks.md, docs/src/tutorials/param_estim.md, src/BPINN_ode.jl, src/advancedHMC_MCMC.jl, test/BPINN_Tests.jl
=> changes from final reviews, improved Docs

.buildkite/pipeline.yml
Remove the extra `steps` that snuck in to run GPU tests on buildkite CI.
Fixes: 12ab042f ("ci: run Documentation builds on buildkite instead of GHA")
=> ci(buildkite): fix GPU tests not being run on Buildkite

.buildkite/pipeline.yml, .github/workflows/CI.yml, .github/workflows/Invalidations.yml
Add any other context about the problem here.
=> version 1.9 to dodge compat bump bandwagon

docs/pages.jl, docs/src/tutorials/ode_parameter_estimation.md, src/dae_solve.jl, src/ode_solve.jl, test/NNODE_tests.jl
=> feat: add Parameter estimation capability in NNODE

src/ode_solve.jl
We were actually doing squared of squared loss as `inner_loss` does the squaring part - https://github.com/SciML/NeuralPDE.jl/blob/master/src/ode_solve.jl#L194
Also fixes: #606
=> refactor: loss functions for NNODE

.github/workflows/CI.yml, src/neural_adapter.jl, src/training_strategies.jl, test/neural_adapter_tests.jl
This is applicable for `Stochastic` and `QuasiRandom` training strategies.
=> fix: bounds of variables in neural adapter setup

docs/src/tutorials/dgm.md, test/dgm_test.jl
Following from the last [comment](https://github.com/SciML/NeuralPDE.jl/pull/802#issuecomment-1976922157) in #802, this reduces the run times for dgm tests.
@sathvikbhagavan @ChrisRackauckas
=> reducing test times for DGM

docs/src/tutorials/integro_diff.md
(None applicable)
Fix up minor formatting
=> Add TeX backticks to math symbols in integro_diff.md

src/pinn_types.jl
Fixes a bug I introduced in #955, which caused `PhysicsInformedNN` to fail to construct in the multioutput case.
=> Fix multioutput `PhysicsInformedNN` construction
